import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Navbar";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex w-full ">
          <div className=" md:w-[6%] lg:w-[12%]">
          <Sidebar />
          </div>
          <div className=" w-full md:w-[94%]  lg:w-[88%]">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
